### ISSUE TITLE
Help in converting nodejs middleware logic into actix web api-proxy

### ISSUE THREAD

**Issue by LironHazan** [greenpress/gateway#8]
Will be happy to get help in converting following nodejs express middleware into actix I think using wrap_fn could be good,
The logic should be executed before the forwarding occur.

1. Intercept a specific request of one of the following proxies: contentService, assetsService, draftsService
2. Check if the request is authorised or contains a "token" on its session cookie - if it does --> next.
3. In case of an un-auth request - initiate a request (we can use the [reqwest](https://crates.io/crates/reqwest) crate)
4. Get the response headers and set the cookie to our intercepted request and then --> next

** const setCookie = response.headers.raw()['set-cookie']

```javascript
(req, res, next) => {
		if (!(req.headers.authorization || req.headers.cookie && req.headers.cookie.includes('token='))) {
			next()
			return
		}
		fetch(meUrl, {
			headers: {
				'Content-Type': 'application/json',
				cookie: req.headers.cookie,
				authorization: req.headers.authorization
			}
		})
			.then(response => {
				const setCookie = response.headers.raw()['set-cookie']
				if (setCookie) {
					res.set('set-cookie', setCookie)
				}
				if (response.status === 200) {
					return response.text()
				}
			})
			.then(user => {
				req.user = user
				next()
			})
			.catch(() => {
				next()
			})
```

**Comment by benzuk** [comment]
Yo!

https://github.com/actix/actix-extras/tree/master/actix-web-httpauth

Looks good?

**Comment by LironHazan** [comment]
Thanks @benzuk  
It looks good, I guess I could use that check (instead of an internal function I wrote that parses the request header as well).

But I need to implement that "hack" that happens here --> 
https://github.com/greenpress/blog-front/blob/ebe74c1cdf4b7603efc0e0159f3735fecb5e8433/server/api-proxy.js#L5

@davidmeirlevy please correct me if I got this wrong the flow is:
1. Intercept a specific request of one of the following proxies: contentService, assetsService, draftsService
2. Check if the request is authorised or contains a "token" on its session cookie - if it does --> next.
3. In case of an un-auth request - initiate a request (we can use the [reqwest](https://crates.io/crates/reqwest) crate)
4. Get the response headers and set the cookie to our intercepted request and then --> next

@benzuk will you want to contribute to this one ? :)

**Comment by davidmeirlevy** [comment]
1. You should pass the request to the internal service, even if there is or isn't a cookie or token.
The service will decide if it's ok for him to serve a guest.

2. You should check the authorization if there's a token inside the cookies or inside the headers (authorization bearer).

**Comment by LironHazan** [comment]
@davidmeirlevy let's have a session I want to show you how the suggested auth middleware works.

**Comment by benzuk** [comment]
@LironHazan I'll have time on Saturday. I've never used middleware with Rust before.

**Comment by LironHazan** [comment]
@benzuk great thanks!

**Comment by benzuk** [comment]
@LironHazan Hi, sorry for the delay - I have a shoulder sprain in the morning after a workout. :\

I've spent the last hour understanding our needs. So, we're moving the proxy API outside of your frontend service to our gateway.

Let's break this issue into two steps:

1. We need to add the actix-web-httpauth package to our gateway. :)
2. We need to create a validator function to validate the token and then:

If validated -> We'll send a request (with a token) to the auth service "/api/me" to get the user's data and add it to the request header.

If not validated -> We'll pass the request to the internal service and he'll decide how to serve it.

Cool?

---

1. I think we need to use a .env file for development purposes to quickly set environment variables locally.
2. Also here's a cool example of actix-web-httpauth (see Bearer Authentication Example section).

(1) - https://crates.io/crates/dotenv
(2) - https://turreta.com/2020/06/07/actix-web-basic-and-bearer-authentication-examples/

**Comment by LironHazan** [comment]
@benzuk 
sorry for the delay 
1. sounds cool, I looked into the package and it played well
2. Do you mind syncing with @davidmeirlevy on the flow and future deployment? 
I may be able to get back to it only next week sorry :/

Glad to have you on board! :)

**Comment by davidmeirlevy** [comment]
Hi @benzuk and @LironHazan 
The gateway should always call "/api/me" if there's a an authorization token or a token cookie, the validation is done inside the authentication service, by calling "api/me".

You can use ".env" file locally, but in production or local dev docker composition, your desired environment variables will be loaded as expected.

**Comment by benzuk** [comment]
> Hi @benzuk and @LironHazan
> The gateway should always call "/api/me" if there's a an authorization token or a token cookie, the validation is done inside the authentication service, by calling "api/me".
> 
> You can use ".env" file locally, but in production or local dev docker composition, your desired environment variables will be loaded as expected.

Hey @davidmeirlevy 

What happens if we send a request from a gateway without an access token? How'll the service decide if we can serve the guest?

Yes, of course, we'll only use .env to run the project inside the editor.

**Comment by davidmeirlevy** [comment]
That’s a decision made by the service itself.
The “/api/me” returns also the roles of the existing user.

**Comment by benzuk** [comment]
> That’s a decision made by the service itself.
> The “/api/me” returns also the roles of the existing user.

Great.

Please see #11 and #12 and let me know it's okay if you contribute like that. I haven't seen your contribution instructions.

**Comment by LironHazan** [comment]
@benzuk I merged both of your PR, is it ok to make you the owner of this one?
I'll be happy to be part of the code review but at the moment I won't be part of the development itself, btw there's a slack channel you can join in, I'll be happy to get to know you and share knowledge of Rust in general 
@davidmeirlevy can you add Ben to the channel if he'll want to

**Comment by davidmeirlevy** [comment]
Yes of course, @benzuk can you share your email or your fb/Twitter profile so I can send you the link?
Thank!

**Comment by benzuk** [comment]
@LironHazan Cool.
@davidmeirlevy Sure, ben.ukhanov@gmail.com

**Comment by davidmeirlevy** [comment]
@benzuk invited.
Also you got maintainer permissions to this repo.

**Comment by benukhanov** [comment]
#14 PR.
